 <link rel="stylesheet" href="assets/styles/css/register.css"> 
 <header>
      <nav>
        <img src="/img/Images/vampire-bat.svg" height="56" alt="Nice green circle"/>
        <ul>
          <li><a href="home">Accueil</a></li>
          <li><a href="deconnexion">Deconnexion</a></li>
          <li><a href="admin-progs">Programmations</a></li>
          <li><a href="admin-artist">Artistes</a></li>
        </ul>
      </nav>
    </header>
