<link rel="stylesheet" href="assets/styles/css/header.css"> 
 <header>
      <nav>
        <img src="/img/Images/vampire-bat.svg" height="56" alt="Nice green circle"/>
        <ul>
          <li><a href="./">Accueil</a></li>
          <li><a href="programmations">Programmations</a></li>
          <li><a href="artists">Artistes</a></li>
          <li><a href="deconnexion">Deconnexion</a></li>
        </ul>
      </nav>
    </header>
