<link rel="stylesheet" href="assets/styles/css/footer.css">
<footer>
<section>
    <h2>OUTRE-TOMBE</h2>
    <article>
        <ul>
             <li class="f-li2">
                        <a href="">
                            <span class="fa-brands fa-facebook-f" alt="facebook"></span>
                        </a>
                    </li>
                    <li class="f-li2">
                         <a href="">
                             <span class="fa fa-pinterest-p"></span>
                         </a>
                    </li>
                    <li class="f-li2">
                         <a href="">
                             <span class="fa fa-instagram"></span>
                         </a>
                    </li>
                    <li class="f-li2">
                       
                            <a href="">
                                <span class="fa fa-twitter"></span>
                            </a>
                        
                    </li>
                    <li class="f-li2">
                         <a href="">
                             <span class="fa fa-youtube-play"></span>
                         </a>
                    </li>
                </ul>
            </article>
            <p>&copy; <?= date('Y'); ?> Jupp. All Rights Reserved.</p>
            </section>
    <article></article>
</section>
</footer>