<link rel="stylesheet" href="assets/styles/css/footer.css">
<footer>
<section class="sectionfooter">
    <h2 class="h2footer">OUTRE-TOMBE</h2>
    <article>
        <ul>
                    
                    <li class="f-li2">
                        <a href="https://www.instagram.com/"><img src="/img/Images/instagram.png" class="listelogo" alt="instagram"></a>
                    </li>
                    <li class="f-li2">
                        <a href="https://www.facebook.com/"><img src="/img/Images/facebook.png" class="listelogo" alt="facebook"></a>
                    </li>
                    <li class="f-li2">
                        <a href="https://twitter.com/home?lang=fr"><img src="/img/Images/twitter.png" class="listelogo" alt="twitter"></a>
                    </li>
                </ul>
            </article>
            <p>&copy; <?= date('Y'); ?> Jupp. All Rights Reserved.</p>
            </section>
</footer>