<link rel="stylesheet" href="assets/styles/css/footer.css">
<footer>
<section>
    <h2>OUTRE-TOMBE</h2>
    <article>
        <ul>
                    <li class="f-li2">
                         <a href="">
                             <span class="fa fa-pinterest-p"></span>
                         </a>
                    </li>
                    <li class="f-li2">
                        <a href=""><img src="/img/Images/instagram.png" class="listelogo" alt="facebook">
                    </li>
                    <li class="f-li2">
                       
                            <a href=""><img src="/img/Images/facebook.png" class="listelogo" alt="facebook">
                        
                    </li>
                    <li class="f-li2">
                            <a href=""><img src="/img/Images/twitter.png" class="listelogo" alt="facebook">
                    </li>
                </ul>
            </article>
            <p>&copy; <?= date('Y'); ?> Jupp. All Rights Reserved.</p>
            </section>
    <article></article>
</section>
</footer>