 <link rel="stylesheet" href="assets/styles/css/style.css"> 
 <header>
      <nav>
        <img src="/img/Images/vampire-bat.svg" height="56" alt="Nice green circle">
        <ul>
          <li><a href="./">Accueil</a></li>
          <li><a href="connexion">Se connecter</a></li>
          <li><a href="creer-un-compte">S'inscrire</a></li>
          <li><a href="programmations">Programmations</a></li>
          <li><a href="artists">Artistes</a></li>
          
        </ul>
      </nav>
    </header>
