 <link rel="stylesheet" href="assets/styles/css/register.css"> 
 <header>
      <nav>
        <img src="/img/Images/vampire-bat.svg" height="68" alt="Nice green circle"/>
        <ul>
          <li><a href="./">Accueil</a></li>
          <li><a href="connexion">Se connecter</a></li>
          <li><a href="programmations">Programmations</a></li>
          <li><a href="#">Billetterie</a></li>
          <li><a href="">Informations</a></li>
        </ul>
      </nav>
    </header>
