


<h1>Ceci est la page de création d'un artiste</h1>

<form method="POST" action="/res03-projet-final/create-artist" enctype="multipart/form-data">
  <fieldset>
  <label>Nom : <input type="text" name="name"></label><br>
  </fieldset>
  <fieldset>
  <label>Slug : <input type="text" name="slug"></label><br>
  </fieldset>
  <fieldset>
  <label>Description : <input type="text" name="description"></label><br>
  </fieldset>
  <fieldset>
  <label>Prix : <input type="text" name="price"></label><br>
  </fieldset>
  <fieldset>
  <input type="file" name="image" />
  </fieldset>
  <input type="submit" value="Envoyer">
</form>