<h1>Ceci est la page de création de programmation</h1>

<form method="POST" action="/res03-projet-final/create-prog" enctype="multipart/form-data">
  <fieldset>
  <label>Nom : <input type="text" name="name"></label><br>
  </fieldset>
  <fieldset>
  <label>Slug : <input type="text" name="slug"></label><br>
  </fieldset>
  <fieldset>
  <label>Description : <input type="text" name="description"></label><br>
  </fieldset>
  <fieldset>
  <input type="submit" value="Envoyer">
</form>