


<h1>Ceci est la page de création d'un artiste</h1>

<form method="POST" action="/create-artist">
  <label>Nom : <input type="text" name="name"></label><br>
  <label>Slug : <input type="text" name="slug"></label><br>
  <label>Description : <input type="text" name="description"></label><br>
  <label>Prix : <input type="text" name="price"></label><br>
  <input type="submit" value="Envoyer">
</form>