<?php var_dump($data) ?>
<h1>Ceci est la page pour modif un artist</h1>
  <form action="/res03-projet-final/edit-artist/<?= $data["edit-artist"]->getSlug(); ?>" method="post" >
      <label for="id">ID</label>
            <input type="text" name="id" id="id" readonly value="<?= $data["edit-artist"]->getId(); ?>">
      <label for="name">Nom du produit :</label>
            <input type="text" name="name" id="name" required value="<?= $data["edit-artist"]->getName(); ?>">
      <label for="description">Description :</label>
            <textarea name="description" id="description"><?= $data["edit-artist"]->getDescription(); ?></textarea>
      <label for="price">Prix</label>
            <input type="text" name="price" id="price" required value="<?= $data["edit-artist"]->getPrice(); ?>">  
      </label>
      <label for="media">Media</label>
            <input type="file" name="image" />  
      </label>
      
            <input type="submit" value="Modifier le produit">
       
            
    </form>