
<!--<link rel="stylesheet" href="assets/styles/css/home.css"> -->
<!-- <header>-->
<!--      <nav>-->
<!--        <img src="/img/Images/vampire-bat.svg" height="68" alt="Nice green circle"/>-->
<!--        <ul>-->
<!--          <li><a href="creer-un-compte">S'inscrire</a></li>-->
<!--          <li><a href="connexion">Se connecter</a></li>-->
<!--          <li><a href="programmations">Programmations</a></li>-->
<!--          <li><a href="billetterie">Billetterie</a></li>-->
<!--        </ul>-->
<!--      </nav>-->
<!--    </header>-->

<h1>
    Ceci est la page d'accueil
</h1>