<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="title" content="Outre-Tombe">
        <meta name="description" content="Site de festival">
        <meta name="author" content="Julien Postec">
        <meta name="keywords" content="Festival, Artistes, Programmation">
        <meta property="og:title" content="Outre-Tombe">
        <meta property="og:description" content="Festival Outre-Tombe">
        <meta property="og:locale" content="fr_FR">
        <meta property="og:image" content="https://images-ext-1.discordapp.net/external/-O0CWDH6ITYYCaiHYqDheLBuobwIHTlgZ5IB6USAOuw/https/ih1.redbubble.net/image.1424702995.4421/fposter%2Csmall%2Cwall_texture%2Cproduct%2C750x1000.jpg?width=503&height=671">
        <title>Outre-Tombe</title>
        <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Creepster&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Risque&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/res03-projet-final/assets/styles/css/style.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-N9X7Pv0Kj+QlEBwFwLqxzfBzKjBnMvlr8chJgMja9ayefyvI+CQ+V8hZwJl2sb7sZtEGsHtIiOGpLuG/LYJq3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />-->
    </head>
    <body>
        <h1 class="sr-only">Outre-tombe</h1>
        <?php
            require $data['header'];
        ?>
        <main>

        <?php
              require  $template.".phtml";
        ?>
        </main>
        <?php
            require 'partials/_footer.phtml';
        ?>
    </body>

</html>


