<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="title" content="">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="referrer" content="">
        <meta property="og:title" content="">
        <meta property="og:description" content="">
        <meta property="og:locale" content="fr_FR">
        <meta property="og:image" content="">
        <meta charset="utf-8">
        <title>Outre-Tombe</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Creepster&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Risque&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="/res03-projet-final/assets/styles/css/style.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-N9X7Pv0Kj+QlEBwFwLqxzfBzKjBnMvlr8chJgMja9ayefyvI+CQ+V8hZwJl2sb7sZtEGsHtIiOGpLuG/LYJq3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <h1 class="sr-only">Outre-tombe</h1>
        <?php
            require $data['header'];
        ?>
        <main>

        <?php
              require  $template.".phtml";
        ?>
        </main>

        <?php
            require 'partials/_footer.phtml';
        ?>

    </body>
</html>


