<link rel="stylesheet" href="assets/styles/css/programmations.css"> 
 <header>
      <nav>
        <img src="/img/Images/vampire-bat.svg" height="68" alt="Nice green circle"/>
        <ul>
          <li><a href="index.php">Accueil</a></li>
          <li><a href="creer-un-compte">S'inscrire</a></li>
          <li><a href="connexion">Se connecter</a></li>
          <li><a href="#">Billetterie</a></li>
        </ul>
      </nav>
    </header>
<h1>Liste des programmations</h1>
