


    <section class="section1register">
    <h2 class="h2register">
        S'inscrire 
    </h2>
    <p class="pregister">
        pour profiter de la newsletter
    </p>
    </section>
    <section class="section2register">
        <article class="articleregister">
    <form method="post" action="/res03-projet-final/check-creer-un-compte" class="col-4"> 
    <h2 class="h2registerform">Créer un compte</h2> 
        <input type="hidden" name="formName" id="formName" value="registerForm" />  
        <fieldset class="mb-3">  
            <label for="username" class="form-label">  
                Nom d'utilisateur  
            </label>  
            <input type="text" name="username" id="username" class="form-control" required />  
        </fieldset>  
        <fieldset class="mb-3">  
            <label for="email" class="form-label">  
                Email  
            </label>  
            <input type="email" name="email" id="email" class="form-control" required />  
        </fieldset>  
        <fieldset class="mb-5">  
            <label for="password" class="form-label">  
                Mot de passe 
            </label>  
            <input type="password" name="password" id="password" class="form-control" required />  
        </fieldset>  
        <fieldset class="mb-5">  
            <label for="confirmPassword" class="form-label">  
                Confirmer le mot de passe
            </label>  
            <input type="password" name="confirmPassword" id="confirmPassword" class="form-control" required />  
        </fieldset>  
        <button type="submit" class="btnregister">Créer un compte</button>  
    </form>
    </article>
    </section>
<script type="module" src="/res03-projet-final/assets/styles/js/validate-user.js"></script>